name: Github Actions workflow for test
on:
  workflow_dispatch

jobs:
  deploy-test:
    name: Deploy test job
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4